version: '2'
services:
  # container for API
  api:
    image: toancong/phpup:2
    ports:
      - 5000:80
    depends_on:
      - db
    volumes:
      - .:/var/www/app
    environment:
      - PHP_MEM_LIMIT=1024M

  # container for Database
  db:
    image: mysql:5.7
    ports:
      - 7000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: user123

  # container for Test Database
  dbtest:
    image: mysql:5.7
    ports:
      - 6000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbtest
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: user123
  # container for dbpdo
  dbpdo:
    image: mysql:5.7
    ports:
      - 1000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbpdo
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: user123
  # container for PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9000:80
    depends_on:
      - db
      - dbtest
      - dbpdo
    environment:
      PMA_HOSTS: db, dbtest,dbpdo
      PMA_USER: dbuser
      PMA_PASSWORD: user123
